# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-
# stub: budgetcrmod 0.5.0 ruby lib

Gem::Specification.new do |s|
  s.name = "budgetcrmod".freeze
  s.version = "0.5.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Edmund Highcock".freeze]
  s.date = "2020-02-08"
  s.description = "A CodeRunner module to help you do your budget".freeze
  s.email = "edmundhighcock@users.sourceforge.net".freeze
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "Gemfile",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "budgetcrmod.gemspec",
    "lib/budgetcrmod.rb",
    "lib/budgetcrmod/account_choices.rb",
    "lib/budgetcrmod/budget.rb",
    "lib/budgetcrmod/defaults_files/budget_defaults.rb",
    "test/helper.rb",
    "test/test_budgetcrmod.rb"
  ]
  s.homepage = "http://github.com/edmundhighcock/budgetcrmod".freeze
  s.licenses = ["MIT".freeze]
  s.rubygems_version = "3.0.6".freeze
  s.summary = "A CodeRunner module to help you do your budget".freeze

  if s.respond_to? :specification_version then
    s.specification_version = 4

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<coderunner>.freeze, [">= 0.11.0"])
      s.add_development_dependency(%q<shoulda>.freeze, [">= 0"])
      s.add_development_dependency(%q<rdoc>.freeze, ["~> 3.12"])
      s.add_development_dependency(%q<bundler>.freeze, ["> 1.0.0"])
      s.add_development_dependency(%q<jeweler>.freeze, [">= 1.8.4"])
    else
      s.add_dependency(%q<coderunner>.freeze, [">= 0.11.0"])
      s.add_dependency(%q<shoulda>.freeze, [">= 0"])
      s.add_dependency(%q<rdoc>.freeze, ["~> 3.12"])
      s.add_dependency(%q<bundler>.freeze, ["> 1.0.0"])
      s.add_dependency(%q<jeweler>.freeze, [">= 1.8.4"])
    end
  else
    s.add_dependency(%q<coderunner>.freeze, [">= 0.11.0"])
    s.add_dependency(%q<shoulda>.freeze, [">= 0"])
    s.add_dependency(%q<rdoc>.freeze, ["~> 3.12"])
    s.add_dependency(%q<bundler>.freeze, ["> 1.0.0"])
    s.add_dependency(%q<jeweler>.freeze, [">= 1.8.4"])
  end
end

